### ISSUE TITLE
The link to Dosebot page on effect index is dead

### ISSUE THREAD

**Issue by OliCB** [dosebotredux/DosebotRedux#14]
On the reply of the about command, the link pointing to Dosebot's page on effect index returns a 404 error. 
https://effectindex.com/dosebot

**Comment by 5HT2** [comment]
Hi, this issue would be better suited for https://github.com/Effecteffectindex/EffectIndex, and I will bring it up there.

**Comment by wjlafrance** [comment]
Thanks @5HT2
